### ISSUE TITLE
Ошибка: Переменная не определена (СтандартныеПодсистемыСервер)

### ISSUE THREAD

**Issue by lospejos** [ivanov660/SimpleDataManager#4]
Запускаю обработку на **1С:Предприятие 8.3 (8.3.22.2175**), конфигурация локальная (не сервер), **полностью кастомная (с нуля), не переделанная типовая**.

Получаю ошибку:
Переменная не определена (СтандартныеПодсистемыСервер)

![image](https://github.com/ivanov660/SimpleDataManager/assets/4608475/ae60a74b-002c-414a-9558-084079c24a3e)

Нужны какие-то обязательные настройки/переменные в конфигурации, чтобы эта внешняя обработка работала?

**Comment by ivanov660** [comment]
> Запускаю обработку на **1С:Предприятие 8.3 (8.3.22.2175**), конфигурация локальная (не сервер), **полностью кастомная (с нуля), не переделанная типовая**.
> 
> Получаю ошибку: Переменная не определена (СтандартныеПодсистемыСервер)
> 
> Нужны какие-то обязательные настройки/переменные в конфигурации, чтобы эта внешняя обработка работала?

1. Это переменная из БСП, название подсистемы. Мы вырезали по максимально зависимость от этой подсистемы
2. Хех. Осталось в механизме регистрации - получении версии. Ждите, скоро обновим релиз с исправлением.

**Comment by ivanov660** [comment]
1. обработку поправили, для возможности открытия в конфигурациях не поддерживающих БСП
2. но в потоках, для конфигураций без БСП по прежнему нет поддержки
